### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by dholth** [conda/conda-index#172]
### Summary

Placeholder for `conda-index YY.M.x` release.

| Pilot | dholth |
|---|---|
| Co-pilot | jezdez |

### Tasks

[milestone]: https://github.com/conda/conda-index/milestone/<milestone>
[process]: https://github.com/conda/conda-index/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-index/releases
[main]: https://github.com/AnacondaRecipes/conda-index-feedstock
[conda-forge]: https://github.com/conda-forge/conda-index-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-index/

<details open>  
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (#168)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-index-YY.M.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process])
- [x] [Publish release][releases]
- [x] Merge `YY.M.x` back into `main`
- [x] Activate the `YY.M.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main]
    - [x] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge]
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)
